version: '3.8'

services:
  nextjs:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3001
      - NEXT_PUBLIC_API_INTERNAL_URL=http://nestjs:3001
      - NEXTAUTH_SECRET=marketplace
    networks:
      - app-network
    depends_on:
      - nestjs

  nestjs:
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://admin:admin123@postgres:5432/mydatabase?schema=public
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
      - SALT_ROUNDS=10
      - JWT_SECRET=my-secret
    networks:
      - app-network
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
